# user defined thresholds for QC

#-----------#
# Sample QC #
#-----------#

# the sample must have more than 1000000 total reads
sqc_total: 1000000

# the missing varaints in the library must be less than 1%
sqc_missing: 0.01

# the sequence must have at least 5 counts in at least 25% of the samples
sqc_low_count: 5
sqc_low_sample_per: 0.25

# the sample must have more than 1000000 reads after the low count filtering
sqc_accepted: 1000000

# the sample must have more than 60% of reads aligned to the library including reference and PAM reads
sqc_mapping_per: 0.6

# the sample must have less than 10% of reads aligned to reference sequence
sqc_ref_per: 0.1

# the sample must have more than 40% of reads aligned to the library
sqc_library_per: 0.4

# the sample must have more than 100x average coverage
# the number of library reads divided by the number of sequences
sqc_library_cov: 100

# the majority of the variants (>70%) distributed above the 0.005% cutoff for the reference samples
sqc_low_per: 0.00005
sqc_low_lib_per: 0.7

#---------------#
# Experiment QC #
#---------------#

# DESeq2 relevant cutoffs
expqc_padj: 0.05
expqc_lfc_depleted: 0
expqc_lfc_enriched: 0
expqc_top_variants: 500

# Log2 Fold Change cutoffs
expqc_lfc_min: -6
expqc_lfc_max: 2
